uploads = []
generated = []

[[outputs]]
id = "I_x25x-3YbGPKY6GkhM75"
uri = "file://arkan-full-source.tar.gz"
type = "unspecified"
title = "أركان — الكود المصدري الكامل (محدّث)"

[[outputs]]
id = "yjq4fvQGZYar8S7KJzitG"
uri = "file://arkan-source.tar.gz"
type = "unspecified"
title = "Arkan - نسخة Windows نهائية"

[[outputs]]
id = "4G6xyP4inNfPbGM5v4e2z"
uri = "file://arkan-windows-v3.tar.gz"
type = "unspecified"
title = "أركان - نسخة Windows v3 الجديدة"

[[outputs]]
id = "kKNxaE9GqRSAXPXViZBT3"
uri = "file://arkan-windows-final.tar.gz"
type = "unspecified"
title = "أركان - جاهز للتشغيل على Windows"
